# Generated by Django 5.2 on 2025-04-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('population', models.IntegerField()),
                ('revenu_median', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicsDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('age_0_14', models.IntegerField()),
                ('age_15_64', models.IntegerField()),
                ('age_65_plus', models.IntegerField()),
                ('revenu_median', models.DecimalField(decimal_places=2, max_digits=15)),
                ('chomage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diplomes_bac_plus_2', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='QualityOfLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('pollution', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_transport', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QualityOfLifeDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('indice_pollution', models.DecimalField(decimal_places=2, max_digits=5)),
                ('espaces_verts', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_transport', models.IntegerField()),
                ('commerces_essentiels', models.IntegerField()),
                ('infrastructure_sante', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('prix_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_ventes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('prix_moyen_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evolution_annuelle', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre_ventes', models.IntegerField()),
                ('type_bien', models.CharField(max_length=50)),
                ('surface_moyenne', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
